let Cdata=[{
    imgs:"https://admin.mynewcar.in/MNC-API/uploads/2715f6e7a01736d9c49a0fea187cc8c0.jpg ",
    title:"Maruti-Suzuki Alto ",
    brand:"Maruthi ",
    description:"The Maruti-Suzuki Alto is a Entry level hatchback that's economical but has basic features & lowquality. Maruti-Suzuki Alto is a available in 5 variants -  LXI (O) Petrol, LXI (O)(CNG), STD (O) Petrol, VXI Petrol, VXI+ Petrol.",
    price:"₹ 4,28,695 ",
},
{
    imgs:"https://admin.mynewcar.in/MNC-API/uploads/8ad92a3822ee6302e91e76e7901b503b.jpg ",
    title:"Hyundai Alcazar ",
    brand:"Hyundai ",
    description:"The Hyundai Alcazar facelift is an eagerly awaited SUV that promises to enhance the already impressive Alcazar.Maruti-Suzuki Alto is a available in 5 variants -  LXI (O) Petrol, LXI (O)(CNG), STD (O) Petrol, VXI Petrol, VXI+ Petrol.",
    price:"₹ 4,28,695 ",
    price:"₹ 20,47,611 ",
},
{
    imgs:"https://imgd.aeplcdn.com/227x128/n/cw/ec/14054/huracan-evo-exterior-right-front-three-quarter-3.jpeg?isig=0&q=80 ",
    title:"Lamborghini Huracan Evo ",
    brand:"Lamborghini ",
    description:"Lamborghini Huracan EvoThe price of Lamborghini Huracan Evo, a 2 seater Coupe, ranges from Rs. 3.22 - 3.73 Crore. It is available in 2 variants, with an engine of 5204 cc and a choice of 1 transmission: Automatic. Huracan Evo comes with 6 airbags. Lamborghini Huracan Evo is available in 14 colours. Users have reported a mileage of 7.25 kmpl for Huracan Evo.",
    price:"₹  3.22 Crore ",
},
{
    imgs:"https://imgd.aeplcdn.com/664x374/n/cw/ec/164543/revuelto-exterior-right-front-three-quarter-2.jpeg?isig=0&q=80",
    title:"Lamborghini Revuelto ",
    brand:"Lamborghini ",
    description:"The price of Lamborghini Revuelto, a 2 seater Coupe, starts from of Rs. 8.89 Crore. It is available in 1 variant, with an engine of 6498 cc and a choice of 1 transmission: Automatic. Revuelto comes with 6 airbags. Lamborghini Revuelto is available in 16 colours..",
    price:" ₹  8.22 Crore ",
},
{
    imgs:"https://imgd.aeplcdn.com/664x374/n/cw/ec/107719/range-rover-exterior-right-front-three-quarter-46.jpeg?isig=0&q=80",
    title:"Land Rover Range Rover Price ",
    brand:"Range Rover ",
    description:"The price of Land Rover Range Rover, a 5 seater SUV, ranges from Rs. 2.39 - 4.17 Crore. It is available in 50 variants, with engine options ranging from 2996 to 4395 cc and a choice of 1 transmission: Automatic",
    price:"₹2.39 - 4.17 Crore ",
},
{
    imgs:"https://imgd.aeplcdn.com/664x374/n/cw/ec/30181/phantom-exterior-right-front-three-quarter.jpeg?isig=0&q=80",
    title:"Rolls-Royce Phantom",
    brand:"Rolls-Royce",
    description:"The Phantom is the pinnacle of luxury motoring. Everything about it is majestic, be it the size, quality, features, or the driving experience.",
    price:"₹ 9.50 Crore",
},
{
    imgs:"https://admin.mynewcar.in/MNC-API/uploads/bfc7a4e7e4803c2cee92c870de6daf60.jpg",
    title:"Mahindra Bolero",
    brand:"Mahindra",
    description:"ThThe Mahindra Bolero is a Favourite 7seat SUV in rural areas for its rugged build quality & low price. Mahindra Bolero is a available in 3 variants - B4 Diesel, B6 Diesel, B6 (O) Diesel.e Hyundai Alcazar facelift is an eagerly awaited SUV that promises to enhance the already impressive Alcazar.",
    price:"₹ 11,60,546",
},
{
    imgs:"https://admin.mynewcar.in/MNC-API/uploads/761462b2c883f8a1df1b9c1b312ac7c3.jpg",
    title:"Maruti-Suzuki Swift",
    brand:"Hyundai ",
    description:"The Hyundai AlcaThe Maruti-Suzuki Swift is a Bestselling sporty & reliable hatch with good fuel economy & features. Maruti-Suzuki Swift is a available in 1 variants - LXI Petrol, VXI Petrol, VXI AGS Petrol,zar facelift is an eagerly awaited SUV that promises to enhance the already impressive Alcazar.",
    price:"₹ 7,86,550 ",
},
{
    imgs:"https://admin.mynewcar.in/MNC-API/uploads/e2b0b9458e17ab5a65a938ddb5bfdf26.jpg",
    title:"Hyundai Creta",
    brand:"Hyundai ",
    description:"The HyHyundai Cretaundai Alcazar facelift is an eagerly awaited SUV that promises to enhance the already impressive Alcazar.",
    price:"₹ 13,78,277 ",
},
{
    imgs:"https://admin.mynewcar.in/MNC-API/uploads/355bac981e79502b0659340431eddee5.jpg",
    title:"Hyundai Venue",
    brand:"Hyundai ",
    description:"The Hyundai Alcazar facelift is aThe Hyundai Venue is a Bestselling compact SUV with boxy design, quality interior & feature rich.n eagerly awaited SUV that promises to enhance the already impressive Alcazar.",
    price:"₹ 9,66,076 ",
},{
    imgs:"https://admin.mynewcar.in/MNC-API/uploads/2a784cc1d511efe5877706060e1071c2.jpg",
    title:"Hyundai Verna",
    brand:"Hyundai ",
    description:"The Hyundai Alcazar faThe Hyundai New Verna is a Sporty sedan with powerful engine, loaded with features & technology. Hyundai New Verna is a available in 10 variants with 2 engine options. celift is an eagerly awaited SUV that promises to enhance the already impressive Alcazar.",
    price:"₹ 18,95,999",
},
{
    imgs:"https://admin.mynewcar.in/MNC-API/uploads/bb28d13237aec79feca30f137be4ba03.jpg ",
    title:"Mahindra XUV 700",
    brand:"Mahindra ",
    description:"The Hyundai Alcazar facelift isThe Mahindra XUV 700 is a Compact SUV with 5 star safety, good performance & mileage. Mahindra XUV 700 is a available in 23 variants - AX 7 AWD Luxury Pack Diesel,AX 7 Luxury Pack Diesel,AX 7 AWD Diesel, an eagerly awaited SUV that promises to enhance the already impressive Alcazar.",
    price:"₹ 20,47,611 ",
},
{
    imgs:"https://admin.mynewcar.in/MNC-API/uploads/69aadeffabac445e52d7a86023701b6a.jpg",
    title:"Mahindra Scorpio N",
    brand:"Mahindra",
    description:"The Hyundai Alcazar facelift is an eagerly awaited SUV that promises to enhance the already impressive Alcazar.Maruti-Suzuki Alto is a available in 5 variants -  LXI (O) Petrol, LXI (O)(CNG), STD (O) Petrol, VXI Petrol, VXI+ Petrol.",
    price:"₹ 4,28,695 ",
    price:"₹ 17,47,611 ",
},
{
    imgs:"https://admin.mynewcar.in/MNC-API/uploads/71ada1418c192f169a32dbfccfb8a4f6.jpg ",
    title:"Mahindra Thar ",
    brand:"Mahindra ",
    description:"The HyundThe Mahindra Thar is a Lifestyle SUV built for offroading with comfort features, soft & hard top option. Mahindra Thar is a available in 13 variants -ai Alcazar facelift is an eagerly awaited SUV that promises to enhance the already impressive Alcazar.",
    price:"₹ 14,47,611 ",
},
{
    imgs:"https://admin.mynewcar.in/MNC-API/uploads/68718fa5bfe7345dea2c76fd7bbba449.jpg",
    title:"Volkswagen Tiguan",
    brand:"Volkswagen ",
    description:"The HyuThe Volkswagen Tiguan is a 5 Seat premium SUV with good built quality, safety & connected car features. Volkswagen Tiguan is a available in 1 variants - Elegancendai Alcazar facelift is an eagerly awaited SUV that promises to enhance the already impressive Alcazar.",
    price:"₹ 44,47,611 ",
},
{
    imgs:" https://admin.mynewcar.in/MNC-API/uploads/971451a0131adef0386f8a2ee91d03c1.jpg",
    title:"Skoda Superb",
    brand:" Skoda  ",
    description:"The Skoda Superb is a Premium sedan with spacious interior, comfortable ride quality & feature rich. Skoda Superb is a available in 2 variants - L&K AT Petrol, SPORTLINE AT Petrol.",
    price:"₹ 42,47,611 ",
},

{
    imgs:"https://admin.mynewcar.in/MNC-API/uploads/733fa7b033642947c289f0ecf4e08fe5.jpg",
    title:" Toyota Innova Crysta ",
    brand:"  Innova Crysta ",
    description:" The Toyota Innova Crysta is a Most comfortable family MPV with good quality interior & rich features. Toyota Innova Crysta is a available in 2 Variants 2.4 GX 7 Seat and 2.4 GX 8 seat.",
    price:"₹  25,02,067 ",
},
{
    imgs:"https://admin.mynewcar.in/MNC-API/uploads/3de7fa119ef9c7b0164c8a9be2295706.jpg",
    title:"Toyota Vellfire ",
    brand:"Toyota ",
    description:"The Toyota Vellfire is a 7seat ultra luxurious MPV with super comfortable interior, hightech features. Toyota Vellfire is a available in 1 variants - The Executive Lounge Electric.",
    price:"₹ 1,48,69,011",
},
{
    imgs:"https://admin.mynewcar.in/MNC-API/uploads/b3b929072391c5b8f1035b7182f12dec.jpg ",
    title:"MG Gloster",
    brand:"MG ",
    description:"The MG Gloster is a 7 seat kingsize premium SUV with connected features & level 1 ADAS. MG Gloster is a available in 6 variants - Savvy-6S-4x4-ADAS Diesel, Sharp-6S-4x4 Diesel, Sharp-7S-4x4 Diesel, Smart-6S-4x2 Diesel, Super-7S-4x2 Diesel, Savvy-7S-4x4 Diesel.",
    price:"₹ 48,34,025",
},
{
    imgs:"https://admin.mynewcar.in/MNC-API/uploads/e3a3efdf0d179b04bca1169c36e0c3b4.jpg ",
    title:"Kia Carnival ",
    brand:"Kia",
    description:"The Kia Carnival is a Premium big family 7 seat MPV with comfortable interior & feature rich. Kia Carnival is a available in 5 variants - D2.2 8AT Limousine 7, The Hyundai Alcazar facelift is an eagerly awaited SUV that promises to enhance the already impressive Alcazar.",
    price:"₹ 38,54,316",
},
{
    imgs:"https://admin.mynewcar.in/MNC-API/uploads/b8981fb0f83194c4be10fbeed226622d.jpg",
    title:"Jeep Meridian ",
    brand:"Jeep ",
    description:"The new Jeep Meridian embodies a unique duality of characteristics; it is big yet sporty, elegant yet rugged, and bold yet sophisticated.",
    price:"₹ 42,61,618 ",
},

]




export default Cdata;